name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Set explicit permissions
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
          
          # Create important GitHub Pages files
          touch dist/.nojekyll
          
          # Ensure camera-icon.svg is in the correct location
          mkdir -p dist/assets
          cp public/camera-icon.svg dist/
          
          # Ensure 404.html is present for SPA routing
          cp public/404.html dist/404.html
          
          # Debug information
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of dist/assets directory:"
          ls -la dist/assets/
          
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VITE_PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
          VITE_PAYPAL_CURRENCY: ${{ secrets.PAYPAL_CURRENCY || 'EUR' }}

      - name: List built files
        run: |
          echo "Listing dist/"
          ls -la dist
          cat dist/index.html   
                 
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true # Remove existing files completely
          single-commit: true